/*
 * generated by Xtext
 */
package jkind.xtext.validation;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import jkind.util.CycleFinder;
import jkind.xtext.jkind.Constant;
import jkind.xtext.jkind.File;
import jkind.xtext.jkind.IdExpr;
import jkind.xtext.jkind.JkindPackage;
import jkind.xtext.util.Util;

import org.eclipse.xtext.EcoreUtil2;
import org.eclipse.xtext.validation.Check;
import org.eclipse.xtext.validation.EValidatorRegistrar;

public class ConstantsAcyclicValidator extends AbstractJKindJavaValidator {
	@Check
	public void checkAcyclic(File file) {
		Map<String, Set<String>> dependencies = getDependencies(file);
		List<String> cycle = CycleFinder.findCycle(dependencies);
		if (cycle != null) {
			error(file, cycle);
		}
	}

	protected Map<String, Set<String>> getDependencies(File file) {
		Map<String, Set<String>> dependencies = new HashMap<>();
		for (Constant c : file.getConstants()) {
			Set<String> set = new HashSet<>();
			for (IdExpr dep : EcoreUtil2.getAllContentsOfType(c, IdExpr.class)) {
				set.add(dep.getId().getName());
			}
			dependencies.put(c.getName(), set);
		}
		return dependencies;
	}

	protected void error(File file, List<String> cycle) {
		String message = "Cycle in constants " + Util.getCycleErrorMessage(cycle);
		Map<String, Constant> table = getConstantTable(file);
		boolean first = true;
		for (String node : cycle) {
			if (first) {
				first = false;
			} else {
				error(message, table.get(node), JkindPackage.Literals.ID_REF__NAME);
			}
		}
	}

	private Map<String, Constant> getConstantTable(File file) {
		Map<String, Constant> table = new HashMap<>();
		for (Constant c : file.getConstants()) {
			table.put(c.getName(), c);
		}
		return table;
	}

	@Override
	public void register(EValidatorRegistrar registrar) {
		// Since this is a composed check we prevent it from registering on its
		// own
	}
}
