/*
 * generated by Xtext
 */
package jkind.xtext.validation;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import jkind.util.CycleFinder;
import jkind.xtext.jkind.File;
import jkind.xtext.jkind.JkindPackage;
import jkind.xtext.jkind.TypeDef;
import jkind.xtext.jkind.UserType;
import jkind.xtext.util.Util;

import org.eclipse.xtext.EcoreUtil2;
import org.eclipse.xtext.validation.Check;
import org.eclipse.xtext.validation.EValidatorRegistrar;

public class TypesAcyclicValidator extends AbstractJKindJavaValidator {
	@Check
	public void checkAcyclic(File file) {
		Map<String, Set<String>> dependencies = getDependencies(file);
		List<String> cycle = CycleFinder.findCycle(dependencies);
		if (cycle != null) {
			error(file, cycle);
		}
	}

	protected Map<String, Set<String>> getDependencies(File file) {
		Map<String, Set<String>> dependencies = new HashMap<>();
		for (TypeDef def : file.getTypedefs()) {
			Set<String> set = new HashSet<>();
			for (UserType dep : EcoreUtil2.getAllContentsOfType(def, UserType.class)) {
				set.add(dep.getDef().getName());
			}
			dependencies.put(def.getName(), set);
		}
		return dependencies;
	}

	protected void error(File file, List<String> cycle) {
		String message = "Cycle in types " + Util.getCycleErrorMessage(cycle);
		Map<String, TypeDef> table = getTypeDefTable(file);
		boolean first = true;
		for (String node : cycle) {
			if (first) {
				first = false;
			} else {
				error(message, table.get(node), JkindPackage.Literals.TYPE_DEF__NAME);
			}
		}
	}

	private Map<String, TypeDef> getTypeDefTable(File file) {
		Map<String, TypeDef> table = new HashMap<>();
		for (TypeDef def : file.getTypedefs()) {
			table.put(def.getName(), def);
		}
		return table;
	}

	@Override
	public void register(EValidatorRegistrar registrar) {
		// Since this is a composed check we prevent it from registering on its
		// own
	}
}
