/*
* generated by Xtext
*/
package jkind.xtext.ui.contentassist;

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
public class JKindProposalProvider extends jkind.xtext.ui.contentassist.AbstractJKindProposalProvider {

}
