/*
* generated by Xtext
*/
package jkind.xtext;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class JKindUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return jkind.xtext.ui.internal.JKindActivator.getInstance().getInjector("jkind.xtext.JKind");
	}
	
}
