/*
 * generated by Xtext
 */
package jkind.xtext;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class JKindRuntimeModule extends jkind.xtext.AbstractJKindRuntimeModule {

}
