/*
 * generated by Xtext
 */
package jkind.xtext.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import jkind.xtext.ui.internal.JKindActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class JKindExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return JKindActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return JKindActivator.getInstance().getInjector(JKindActivator.JKIND_XTEXT_JKIND);
	}
	
}
