/*
 * generated by Xtext
 */
package jkind.xtext.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class JKindUiModule extends jkind.xtext.ui.AbstractJKindUiModule {
	public JKindUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
